version: '2'
services:
  fitapp-node:
    restart: always
    build: .
    container_name: fitapp-node
    ports:
      - '3000:3000'
      - '5858:5858'
      - '8080:8080'
      - '35729:35729'
    environment:
      - NODE_ENV=development
      - PORT=3000
